name: Combine Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Combine Markdown files
      run: |
        echo "# My Software Engineering Notes" > README.md
        for file in Notes/*.md; do
          filename=$(basename "$file" .md)
          title=$(echo "$filename" | sed 's/^[0-9]*_//' | sed 's/_/ /g')
          echo -e "\n## $title" >> README.md
          echo "<details>" >> README.md
          echo "  <summary><h2 style='display: inline;'> $title </h2></summary><br>" >> README.md
          echo "  " >> README.md
          # Replace './Images' with './Notes/Images' before appending content
          sed 's/\.\//.\/Notes\//' "$file" | sed 's/^/  /' >> README.md
          echo -e "\n</details>" >> README.md
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m 'Update README.md with combined notes'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
